### ISSUE TITLE
Vtex speed start error

### ISSUE THREAD

**Issue by iraima20** [vtex/speed#28]
**Você quer pedir uma nova feature ou reportar um bug?**
Reportar un bug
**Qual o comportamento atual?**
No logro iniciar el vtex speed con el npm

**Se o comportamento atual é um bug, por favor, forneça os passos para reproduzir o problema.**
npm install - ok
npm start - Error!
Error: Failed at the vtex-speed@3.1.0 start script 'grunt'
This is most likely a problem with the vtex speed package,
not with npm itself.

**Qual browser e sistema operacional são afetados por esse problema?**
Windows 10

Node v4.5.0
npm 2.15.9

`0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@2.15.9
3 info using node@v4.5.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info prestart vtex-speed@3.1.0
6 info start vtex-speed@3.1.0
7 verbose unsafe-perm in lifecycle true
8 info vtex-speed@3.1.0 Failed to exec start script
9 verbose stack Error: vtex-speed@3.1.0 start: `grunt`
9 verbose stack Exit status 1
9 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:217:16)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at EventEmitter.emit (events.js:172:7)
9 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:24:14)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at ChildProcess.emit (events.js:172:7)
9 verbose stack     at maybeClose (internal/child_process.js:829:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
10 verbose pkgid vtex-speed@3.1.0
11 verbose cwd C:\Users\PERSONAL\Desktop\MAERSOFT\prueba-vtex\speed-master
12 error Windows_NT 10.0.14393
13 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
14 error node v4.5.0
15 error npm  v2.15.9
16 error code ELIFECYCLE
17 error vtex-speed@3.1.0 start: `grunt`
17 error Exit status 1
18 error Failed at the vtex-speed@3.1.0 start script 'grunt'.
18 error This is most likely a problem with the vtex-speed package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     grunt
18 error You can get information on how to open an issue for this project with:
18 error     npm bugs vtex-speed
18 error Or if that isn't available, you can get their info via:
18 error
18 error     npm owner ls vtex-speed
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]`

**Comment by brenoc** [comment]
Can you try using npm version 3 and tell me if this problem still happen, please?
